name: in_app_purchase_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Shared Preferences
  shared_preferences: ^0.5.2

  # in App Purchase
  in_app_purchase: ^0.3.4+5

  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

